### ISSUE TITLE
NPE at org.eclipse.lsp4e.LSPEclipseUtils.toUri(LSPEclipseUtils.java:673)

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#131]
I see the following NPE in my log. Please report upstream and fix if possible.

```
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4e.LSPEclipseUtils.toUri(LSPEclipseUtils.java:673)
	at org.eclipse.lsp4e.LSPEclipseUtils.toUri(LSPEclipseUtils.java:677)
	at org.eclipse.lsp4e.LSPEclipseUtils.toUri(LSPEclipseUtils.java:924)
	at org.eclipse.lsp4e.LSPEclipseUtils.lambda$14(LSPEclipseUtils.java:913)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.eclipse.lsp4e.LSPEclipseUtils.findOpenEditorsFor(LSPEclipseUtils.java:919)
	at org.eclipse.lsp4e.operations.diagnostics.LSPDiagnosticsToMarkers.accept(LSPDiagnosticsToMarkers.java:85)
	at org.eclipse.lsp4e.LanguageClientImpl.publishDiagnostics(LanguageClientImpl.java:72)
	... 16 more
```

**Comment by arteck** [comment]
here same.. any ideas ???

**Comment by vogella** [comment]
@jonas-jonas can you follow-up?

**Comment by vogella** [comment]
@arteck so the bug is fixed upstream?

**Comment by jonas-jonas** [comment]
I think this has been fixed. Please re-open if it re-appears.
