### ISSUE TITLE
Oomph task for p2 installation fails

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#159]
@merks contributed the Dartboard Oomph task but the p2 task fails 
````

ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:426)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:338)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:815)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3827)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3755)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3736)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3629)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:582)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:708)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1578583151558
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Tycho Project Configurators 0.8.1.201704211436 (org.sonatype.tycho.m2e 0.8.1.201704211436) requires 'osgi.bundle; org.eclipse.m2e.core [1.4.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1578583151558
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.tycho.m2e.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Tycho Project Configurators 0.8.1.201704211436 (org.sonatype.tycho.m2e.feature.feature.group 0.8.1.201704211436)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.tycho.m2e [0.8.1.201704211436,0.8.1.201704211436]

````

@merks I guess the p2 update site is broken. Did you already face this already in another project and are aware of a working update site for this?

**Comment by vogella** [comment]
The above commit removes temporary the p2 task until we learn which URl we should use.

**Comment by merks** [comment]
To fix problems like this I always use the approach described here:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring#How_to_find_a_P2_repository_at_Eclipse_using_the_Repository_Explorer

Unfortunately they don't provide very nice sites.  I.e., there is no site with just the latest release or just the latest milestones.   

The best they seem to have that should always work is:

https://download.eclipse.org/technology/m2e/releases/

But it contains all releases so is big and therefore slow.
